// src/constants/demo-users/plans/aviPlan.ts
// 📋 תוכנית אימון אבי כהן - Push/Pull/Legs מתקדמת

import type { DemoPlanConfig } from "./types";

/**
 * 💪 תוכנית Push/Pull/Legs לאבי כהן
 * מתמחה בבניית כוח ומסה עם חלוקה קלאסית למקבוצות שרירים
 */
export const aviPlan: DemoPlanConfig = {
  id: "plan-avi-push-pull-legs",
  name: "Push/Pull/Legs - אבי",
  description:
    "תוכנית מתקדמת לבניית כוח ומסה עם חלוקה לימי דחיפה, משיכה ורגליים",
  difficulty: "intermediate",
  creator: "Gymovo AI",
  targetMuscleGroups: ["חזה", "גב", "רגליים", "כתפיים", "זרועות"],
  durationWeeks: 12,
  weeklyGoal: 5,
  tags: ["power", "muscle_gain", "intermediate"],
  rating: 5,
  createdAt: "2024-10-01T10:00:00Z",
  updatedAt: "2024-12-01T10:00:00Z",
  userId: "demo-user-avi",
  isActive: true,
  days: [
    {
      id: "avi-day-push",
      name: "יום דחיפה - חזה, כתפיים, יד אחורית",
      estimatedDuration: 75,
      targetMuscleGroups: ["חזה", "כתפיים", "יד אחורית"],
      difficulty: "intermediate",
      exercises: [
        {
          id: "avi-bench-press",
          name: "לחיצת חזה במוט",
          muscleGroup: "חזה",
          sets: 4,
          reps: 8,
          weight: 80,
          restTime: 120,
          notes: "התמקד בטכניקה נכונה",
        },
        {
          id: "avi-incline-db",
          name: "לחיצת חזה שיפוע עם משקולות",
          muscleGroup: "חזה",
          sets: 3,
          reps: 10,
          weight: 30,
          restTime: 90,
        },
        {
          id: "avi-shoulder-press",
          name: "לחיצת כתפיים עם משקולות",
          muscleGroup: "כתפיים",
          sets: 3,
          reps: 12,
          weight: 22,
          restTime: 90,
        },
        {
          id: "avi-lateral-raise",
          name: "הרמות לצדדים",
          muscleGroup: "כתפיים",
          sets: 3,
          reps: 15,
          weight: 12,
          restTime: 60,
        },
        {
          id: "avi-tricep-pushdown",
          name: "פשיטת מרפקים בפולי",
          muscleGroup: "יד אחורית",
          sets: 3,
          reps: 12,
          weight: 35,
          restTime: 60,
        },
        {
          id: "avi-overhead-tricep",
          name: "פשיטה מעל הראש",
          muscleGroup: "יד אחורית",
          sets: 3,
          reps: 10,
          weight: 20,
          restTime: 60,
        },
      ],
    },
    {
      id: "avi-day-pull",
      name: "יום משיכה - גב, יד קדמית",
      estimatedDuration: 70,
      targetMuscleGroups: ["גב", "יד קדמית"],
      difficulty: "intermediate",
      exercises: [
        {
          id: "avi-pullups",
          name: "מתח",
          muscleGroup: "גב",
          sets: 4,
          reps: 8,
          weight: 10,
          restTime: 120,
          notes: "עם משקל נוסף או עזרה",
        },
        {
          id: "avi-barbell-row",
          name: "חתירה עם מוט",
          muscleGroup: "גב",
          sets: 4,
          reps: 10,
          weight: 60,
          restTime: 90,
        },
        {
          id: "avi-lat-pulldown",
          name: "משיכת פולי עליון",
          muscleGroup: "גב",
          sets: 3,
          reps: 12,
          weight: 55,
          restTime: 90,
        },
        {
          id: "avi-cable-row",
          name: "חתירה בפולי נמוך",
          muscleGroup: "גב",
          sets: 3,
          reps: 12,
          weight: 50,
          restTime: 90,
        },
        {
          id: "avi-bicep-curl",
          name: "כפיפת מרפקים עם משקולות",
          muscleGroup: "יד קדמית",
          sets: 3,
          reps: 12,
          weight: 18,
          restTime: 60,
        },
        {
          id: "avi-hammer-curl",
          name: "כפיפת פטיש",
          muscleGroup: "יד קדמית",
          sets: 3,
          reps: 10,
          weight: 20,
          restTime: 60,
        },
      ],
    },
    {
      id: "avi-day-legs",
      name: "יום רגליים - רגליים מלא",
      estimatedDuration: 80,
      targetMuscleGroups: ["רגליים", "שוקיים"],
      difficulty: "intermediate",
      exercises: [
        {
          id: "avi-squat",
          name: "סקוואט עם מוט",
          muscleGroup: "רגליים",
          sets: 4,
          reps: 8,
          weight: 100,
          restTime: 150,
          notes: "עומק מלא",
        },
        {
          id: "avi-romanian-deadlift",
          name: "דדליפט רומני",
          muscleGroup: "רגליים",
          sets: 4,
          reps: 10,
          weight: 80,
          restTime: 120,
        },
        {
          id: "avi-leg-press",
          name: "לחיצת רגליים במכונה",
          muscleGroup: "רגליים",
          sets: 3,
          reps: 15,
          weight: 120,
          restTime: 90,
        },
        {
          id: "avi-leg-curl",
          name: "כפיפת רגליים שכיבה",
          muscleGroup: "רגליים",
          sets: 3,
          reps: 12,
          weight: 40,
          restTime: 90,
        },
        {
          id: "avi-calf-raises",
          name: "הרמות עקבים",
          muscleGroup: "שוקיים",
          sets: 4,
          reps: 20,
          weight: 60,
          restTime: 60,
        },
      ],
    },
  ],
};
