// src/constants/demo-users/plans/mayaPlan.ts
// 📋 תוכנית אימון מאיה לוי - HIIT + Strength מתקדמת

import type { DemoPlanConfig } from "./types";

/**
 * 🏃‍♀️ תוכנית HIIT + Strength למאיה לוי
 * משלבת אימוני אינטרוול גבוה עם אימוני כוח לחיטוב וביצועים
 */
export const mayaPlan: DemoPlanConfig = {
  id: "plan-maya-hiit-strength",
  name: "HIIT + Strength - מאיה",
  description: "תוכנית מתקדמת המשלבת אימוני HIIT עם אימוני כוח לחיטוב וביצועים",
  difficulty: "advanced",
  creator: "Gymovo AI",
  targetMuscleGroups: ["כל הגוף", "ליבה", "חזה", "רגליים"],
  durationWeeks: 8,
  weeklyGoal: 6,
  tags: ["hiit", "weight_loss", "advanced", "endurance"],
  rating: 5,
  createdAt: "2024-09-15T10:00:00Z",
  updatedAt: "2024-12-01T10:00:00Z",
  userId: "demo-user-maya",
  isActive: true,
  days: [
    {
      id: "maya-day-hiit-upper",
      name: "HIIT חלק עליון",
      estimatedDuration: 45,
      targetMuscleGroups: ["חזה", "גב", "כתפיים", "ליבה"],
      difficulty: "advanced",
      exercises: [
        {
          id: "maya-burpees",
          name: "ברפיז",
          muscleGroup: "כל הגוף",
          sets: 4,
          reps: 15,
          weight: 0,
          restTime: 30,
          notes: "30 שניות מאמץ, 30 שניות מנוחה",
        },
        {
          id: "maya-pushup-variations",
          name: "שכיבות סמיכה - וריאציות",
          muscleGroup: "חזה",
          sets: 3,
          reps: 12,
          weight: 0,
          restTime: 45,
        },
        {
          id: "maya-db-thrusters",
          name: "משקולות דחיפה מעל הראש",
          muscleGroup: "כתפיים",
          sets: 3,
          reps: 15,
          weight: 12,
          restTime: 60,
        },
        {
          id: "maya-mountain-climbers",
          name: "מטפסי הרים",
          muscleGroup: "ליבה",
          sets: 3,
          reps: 20,
          weight: 0,
          restTime: 30,
        },
        {
          id: "maya-plank-variations",
          name: "פלאנק - וריאציות",
          muscleGroup: "ליבה",
          sets: 3,
          reps: 45,
          weight: 0,
          restTime: 45,
          notes: "שניות החזקה",
        },
      ],
    },
    {
      id: "maya-day-strength-lower",
      name: "כוח רגליים",
      estimatedDuration: 50,
      targetMuscleGroups: ["רגליים", "שוקיים"],
      difficulty: "advanced",
      exercises: [
        {
          id: "maya-squat-jumps",
          name: "סקוואט קפיצות",
          muscleGroup: "רגליים",
          sets: 4,
          reps: 12,
          weight: 0,
          restTime: 60,
        },
        {
          id: "maya-bulgarian-split",
          name: "סקוואט בולגרי",
          muscleGroup: "רגליים",
          sets: 3,
          reps: 12,
          weight: 15,
          restTime: 90,
          notes: "כל רגל בנפרד",
        },
        {
          id: "maya-deadlift-sumo",
          name: "דדליפט סומו",
          muscleGroup: "רגליים",
          sets: 4,
          reps: 10,
          weight: 60,
          restTime: 120,
        },
        {
          id: "maya-walking-lunges",
          name: "זינוקים הליכה",
          muscleGroup: "רגליים",
          sets: 3,
          reps: 16,
          weight: 20,
          restTime: 90,
        },
        {
          id: "maya-single-calf",
          name: "הרמות עקבים יחיד",
          muscleGroup: "שוקיים",
          sets: 3,
          reps: 15,
          weight: 25,
          restTime: 60,
          notes: "כל רגל בנפרד",
        },
      ],
    },
    {
      id: "maya-day-circuit",
      name: "מעגל כל הגוף",
      estimatedDuration: 40,
      targetMuscleGroups: ["כל הגוף"],
      difficulty: "advanced",
      exercises: [
        {
          id: "maya-kettlebell-swing",
          name: "נדנוד קטלבל",
          muscleGroup: "כל הגוף",
          sets: 4,
          reps: 20,
          weight: 16,
          restTime: 45,
        },
        {
          id: "maya-bear-crawl",
          name: "זחילת דוב",
          muscleGroup: "כל הגוף",
          sets: 3,
          reps: 30,
          weight: 0,
          restTime: 60,
          notes: "שניות תנועה",
        },
        {
          id: "maya-db-man-makers",
          name: "משקולות איש יוצר",
          muscleGroup: "כל הגוף",
          sets: 3,
          reps: 8,
          weight: 12,
          restTime: 90,
        },
        {
          id: "maya-high-knees",
          name: "הרמת ברכיים גבוה",
          muscleGroup: "כל הגוף",
          sets: 3,
          reps: 30,
          weight: 0,
          restTime: 30,
          notes: "שניות מהירות",
        },
      ],
    },
  ],
};
