// src/constants/demo-users/plans/yoniPlan.ts
// 📋 תוכנית אימון יוני רוזן - מתחילים ידידותית

import type { DemoPlanConfig } from "./types";

/**
 * 🌱 תוכנית מתחילים ליוני רוזן
 * בסיסית ועדינה עם דגש על טכניקה נכונה וביטחון
 */
export const yoniPlan: DemoPlanConfig = {
  id: "plan-yoni-beginner-full",
  name: "מתחילים מלא - יוני",
  description: "תוכנית בסיסית ועדינה למתחילים עם דגש על טכניקה נכונה וביטחון",
  difficulty: "beginner",
  creator: "Gymovo AI",
  targetMuscleGroups: ["כל הגוף", "ליבה"],
  durationWeeks: 6,
  weeklyGoal: 3,
  tags: ["beginner", "safety", "technique", "basic"],
  rating: 4,
  createdAt: "2024-11-01T10:00:00Z",
  updatedAt: "2024-12-01T10:00:00Z",
  userId: "demo-user-yoni",
  isActive: true,
  days: [
    {
      id: "yoni-day-basic-upper",
      name: "בסיסי חלק עליון",
      estimatedDuration: 30,
      targetMuscleGroups: ["חזה", "גב", "זרועות"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-wall-pushup",
          name: "שכיבות סמיכה על קיר",
          muscleGroup: "חזה",
          sets: 2,
          reps: 8,
          weight: 0,
          restTime: 90,
          notes: "התחל בקלות, התמקד בטכניקה",
        },
        {
          id: "yoni-assisted-pullup",
          name: "מתח בעזרה",
          muscleGroup: "גב",
          sets: 2,
          reps: 5,
          weight: 0,
          restTime: 120,
          notes: "השתמש בגומיה או בעזרת חבר",
        },
        {
          id: "yoni-light-db-press",
          name: "לחיצת משקולות קלות",
          muscleGroup: "חזה",
          sets: 2,
          reps: 10,
          weight: 5,
          restTime: 90,
        },
        {
          id: "yoni-arm-circles",
          name: "סיבובי זרועות",
          muscleGroup: "כתפיים",
          sets: 2,
          reps: 15,
          weight: 0,
          restTime: 30,
          notes: "חימום וחיזוק בסיסי",
        },
        {
          id: "yoni-light-bicep",
          name: "כפיפות זרוע קלות",
          muscleGroup: "יד קדמית",
          sets: 2,
          reps: 12,
          weight: 3,
          restTime: 60,
        },
      ],
    },
    {
      id: "yoni-day-basic-lower",
      name: "בסיסי רגליים",
      estimatedDuration: 25,
      targetMuscleGroups: ["רגליים", "ליבה"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-bodyweight-squat",
          name: "סקוואט משקל גוף",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 10,
          weight: 0,
          restTime: 90,
          notes: "התמקד בעומק נכון",
        },
        {
          id: "yoni-wall-sit",
          name: "ישיבה על קיר",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 20,
          weight: 0,
          restTime: 90,
          notes: "שניות החזקה",
        },
        {
          id: "yoni-basic-lunges",
          name: "זינוקים בסיסיים",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 8,
          weight: 0,
          restTime: 90,
          notes: "כל רגל בנפרד",
        },
        {
          id: "yoni-calf-raise-basic",
          name: "הרמות עקבים בסיסי",
          muscleGroup: "שוקיים",
          sets: 2,
          reps: 15,
          weight: 0,
          restTime: 60,
        },
        {
          id: "yoni-basic-plank",
          name: "פלאנק בסיסי",
          muscleGroup: "ליבה",
          sets: 2,
          reps: 15,
          weight: 0,
          restTime: 90,
          notes: "שניות החזקה",
        },
      ],
    },
    {
      id: "yoni-day-flexibility",
      name: "גמישות ושיקום",
      estimatedDuration: 20,
      targetMuscleGroups: ["כל הגוף"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-cat-cow",
          name: "חתול פרה",
          muscleGroup: "גב",
          sets: 2,
          reps: 10,
          weight: 0,
          restTime: 30,
          notes: "תנועה איטית וחלקה",
        },
        {
          id: "yoni-child-pose",
          name: "תנוחת הילד",
          muscleGroup: "גב",
          sets: 2,
          reps: 30,
          weight: 0,
          restTime: 0,
          notes: "שניות מתיחה",
        },
        {
          id: "yoni-leg-swings",
          name: "נדנודי רגל",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 10,
          weight: 0,
          restTime: 30,
          notes: "כל רגל בנפרד",
        },
        {
          id: "yoni-arm-stretch",
          name: "מתיחת זרועות",
          muscleGroup: "זרועות",
          sets: 2,
          reps: 15,
          weight: 0,
          restTime: 30,
          notes: "שניות החזקה לכל צד",
        },
        {
          id: "yoni-deep-breathing",
          name: "נשימות עמוקות",
          muscleGroup: "ליבה",
          sets: 1,
          reps: 10,
          weight: 0,
          restTime: 0,
          notes: "התמקד בנשימה",
        },
      ],
    },
  ],
};
