// src/constants/demo-users/plans/yoniPlan.ts
// 📋 תוכנית אימון יוני רוזן - נבנתה על בסיס שאלון

import type { DemoPlanConfig } from "./types";

/**
 * 🌱 תוכנית בניית שריר ליוני רוזן
 * נבנתה אוטומטית על בסיס השאלון: hypertrophy, beginner, gym, 3 days/week
 */
export const yoniPlan: DemoPlanConfig = {
  id: "plan-yoni-hypertrophy-beginner",
  name: "תוכנית לבניית שריר - יוני",
  description:
    "תוכנית אימון מותאמת אישית לרמת מתחילים עם מטרת בניית שריר. נוצרה על בסיס השאלון האישי שלך ומותאמת לחדר כושר.",
  difficulty: "beginner",
  creator: "Gymovo AI",
  targetMuscleGroups: ["חזה", "גב", "רגליים", "כתפיים", "זרועות"],
  durationWeeks: 8,
  weeklyGoal: 3,
  tags: ["hypertrophy", "beginner", "AI-generated"],
  rating: 4,
  createdAt: "2024-11-01T10:00:00Z",
  updatedAt: "2024-12-01T10:00:00Z",
  userId: "demo-user-yoni",
  isActive: true,
  days: [
    {
      id: "yoni-day-full-body-1",
      name: "יום עליון - Full Body",
      estimatedDuration: 40,
      targetMuscleGroups: ["חזה", "גב", "כתפיים"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-chest-press",
          name: "דחיפת חזה",
          muscleGroup: "חזה",
          sets: 2,
          reps: 10,
          weight: 30,
          restTime: 90,
          notes: "התחל עם משקל קל, התמקד בטכניקה",
        },
        {
          id: "yoni-lat-pulldown",
          name: "משיכת לאט",
          muscleGroup: "גב",
          sets: 2,
          reps: 10,
          weight: 35,
          restTime: 90,
          notes: "משוך לכיוון החזה העליון",
        },
        {
          id: "yoni-shoulder-press",
          name: "דחיפת כתפיים",
          muscleGroup: "כתפיים",
          sets: 2,
          reps: 10,
          weight: 20,
          restTime: 90,
          notes: "שמור על גב ישר",
        },
        {
          id: "yoni-bent-over-row",
          name: "חתירה",
          muscleGroup: "גב",
          sets: 2,
          reps: 10,
          weight: 25,
          restTime: 90,
          notes: "משוך למרפק, לא לכף היד",
        },
        {
          id: "yoni-plank",
          name: "פלאנק",
          muscleGroup: "ליבה",
          sets: 2,
          reps: 20,
          weight: 0,
          restTime: 90,
          notes: "שניות החזקה",
        },
      ],
    },
    {
      id: "yoni-day-full-body-2",
      name: "יום תחתון - Full Body",
      estimatedDuration: 35,
      targetMuscleGroups: ["רגליים", "ליבה"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-squat",
          name: "סקוואט",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 10,
          weight: 40,
          restTime: 90,
          notes: "רד עד זווית 90 מעלות",
        },
        {
          id: "yoni-leg-press",
          name: "דחיפת רגליים",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 10,
          weight: 60,
          restTime: 90,
          notes: "התחל עם משקל בטוח",
        },
        {
          id: "yoni-calf-raise",
          name: "הרמת עקבים",
          muscleGroup: "רגליים",
          sets: 2,
          reps: 12,
          weight: 20,
          restTime: 60,
          notes: "עלה למקסימום וחזור לאט",
        },
        {
          id: "yoni-crunches",
          name: "קראנצ'ים",
          muscleGroup: "ליבה",
          sets: 2,
          reps: 12,
          weight: 0,
          restTime: 60,
          notes: "אל תמשוך בצוואר",
        },
        {
          id: "yoni-russian-twist",
          name: "סיבוב רוסי",
          muscleGroup: "ליבה",
          sets: 2,
          reps: 15,
          weight: 0,
          restTime: 60,
          notes: "כל צד בנפרד",
        },
      ],
    },
    {
      id: "yoni-day-full-body-3",
      name: "גוף מלא - Full Body",
      estimatedDuration: 45,
      targetMuscleGroups: ["כל הגוף"],
      difficulty: "beginner",
      exercises: [
        {
          id: "yoni-push-up",
          name: "שכיבות סמיכה",
          muscleGroup: "חזה",
          sets: 2,
          reps: 8,
          weight: 0,
          restTime: 90,
          notes: "אם קשה, עשה על הברכיים",
        },
        {
          id: "yoni-cable-row",
          name: "חתירת כבל",
          muscleGroup: "גב",
          sets: 2,
          reps: 10,
          weight: 30,
          restTime: 90,
          notes: "שמור על גב ישר",
        },
        {
          id: "yoni-bicep-curl",
          name: "סיבוב ביצפס",
          muscleGroup: "זרועות",
          sets: 2,
          reps: 10,
          weight: 10,
          restTime: 60,
          notes: "תנועה מבוקרת בלבד",
        },
        {
          id: "yoni-tricep-extension",
          name: "הארכת טריצפס",
          muscleGroup: "זרועות",
          sets: 2,
          reps: 10,
          weight: 15,
          restTime: 60,
          notes: "שמור על כתפיים יציבות",
        },
        {
          id: "yoni-lateral-raise",
          name: "הרמה צידית",
          muscleGroup: "כתפיים",
          sets: 2,
          reps: 10,
          weight: 8,
          restTime: 60,
          notes: "עד גובה הכתפיים",
        },
      ],
    },
  ],
};
