// src/constants/demoPlans.ts - גרסה מתוקנת עם כל השדות הנדרשים
import { Plan } from "../types/plan";

export const demoPlans: Plan[] = [
  {
    id: "plan_ppl_1",
    name: "תוכנית כוח - PPL",
    description: "תוכנית קלאסית בחלוקת Push, Pull, Legs לבניית כוח ומסה.",
    difficulty: "intermediate",
    creator: "Gymovo Demo",

    // 📊 נתונים נדרשים
    createdAt: "2024-01-01T10:00:00.000Z",
    updatedAt: "2024-01-01T10:00:00.000Z",
    userId: "demo_user",
    isActive: true,
    rating: 4.5,
    weeklyGoal: 3,
    tags: ["כוח", "מסה", "PPL"],

    days: [
      {
        id: "day_ppl_push",
        name: "יום א' - Push (חזה, כתפיים, יד אחורית)",
        estimatedDuration: 60,
        difficulty: "intermediate",
        targetMuscleGroups: ["חזה", "כתפיים", "יד אחורית"],
        exercises: [
          {
            id: "ex_bench_press",
            name: "לחיצת חזה במוט",
            muscleGroup: "חזה",
            sets: 4,
            reps: 8,
            weight: 80,
            restTime: 180,
          },
          {
            id: "ex_incline_db_press",
            name: "לחיצת חזה בשיפוע חיובי עם משקולות",
            muscleGroup: "חזה",
            sets: 3,
            reps: 10,
            weight: 30,
            restTime: 120,
          },
          {
            id: "ex_shoulder_press",
            name: "לחיצת כתפיים עם משקולות",
            muscleGroup: "כתפיים",
            sets: 3,
            reps: 10,
            weight: 20,
            restTime: 120,
          },
          {
            id: "ex_lateral_raises",
            name: "הרמות צד עם משקולות",
            muscleGroup: "כתפיים",
            sets: 3,
            reps: 15,
            weight: 8,
            restTime: 90,
          },
          {
            id: "ex_tricep_pushdown",
            name: "פשיטת מרפקים בפולי עליון",
            muscleGroup: "יד אחורית",
            sets: 3,
            reps: 12,
            weight: 25,
            restTime: 90,
          },
          {
            id: "ex_overhead_tricep",
            name: "פשיטת מרפקים מעל הראש",
            muscleGroup: "יד אחורית",
            sets: 3,
            reps: 12,
            weight: 15,
            restTime: 90,
          },
        ],
      },
      {
        id: "day_ppl_pull",
        name: "יום ב' - Pull (גב, יד קדמית)",
        estimatedDuration: 65,
        difficulty: "intermediate",
        targetMuscleGroups: ["גב", "יד קדמית"],
        exercises: [
          {
            id: "ex_pullups",
            name: "מתח (עם/בלי עזרה)",
            muscleGroup: "גב",
            sets: 4,
            reps: 8,
            restTime: 180,
            notes: "אם לא מצליח ללא עזרה, השתמש במכונת עזרה",
          },
          {
            id: "ex_barbell_row",
            name: "חתירה עם מוט",
            muscleGroup: "גב",
            sets: 4,
            reps: 10,
            weight: 60,
            restTime: 150,
          },
          {
            id: "ex_lat_pulldown",
            name: "משיכת פולי עליון",
            muscleGroup: "גב",
            sets: 3,
            reps: 12,
            weight: 50,
            restTime: 120,
          },
          {
            id: "ex_cable_row",
            name: "חתירה בכבל ישיבה",
            muscleGroup: "גב",
            sets: 3,
            reps: 12,
            weight: 45,
            restTime: 120,
          },
          {
            id: "ex_bicep_curl",
            name: "כפיפת מרפקים עם משקולות",
            muscleGroup: "יד קדמית",
            sets: 3,
            reps: 12,
            weight: 15,
            restTime: 90,
          },
          {
            id: "ex_hammer_curl",
            name: "כפיפת פטיש עם משקולות",
            muscleGroup: "יד קדמית",
            sets: 3,
            reps: 12,
            weight: 12,
            restTime: 90,
          },
        ],
      },
      {
        id: "day_ppl_legs",
        name: "יום ג' - Legs (רגליים)",
        estimatedDuration: 70,
        difficulty: "intermediate",
        targetMuscleGroups: ["רגליים", "שוקיים"],
        exercises: [
          {
            id: "ex_squat",
            name: "סקוואט עם מוט",
            muscleGroup: "רגליים",
            sets: 4,
            reps: 8,
            weight: 100,
            restTime: 180,
            notes: "שמור על גב ישר ויורד עד זווית 90 מעלות",
          },
          {
            id: "ex_leg_press",
            name: "לחיצת רגליים במכונה",
            muscleGroup: "רגליים",
            sets: 4,
            reps: 10,
            weight: 120,
            restTime: 150,
          },
          {
            id: "ex_romanian_deadlift",
            name: "דדליפט רומני",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 12,
            weight: 70,
            restTime: 120,
          },
          {
            id: "ex_leg_curl",
            name: "כפיפת רגליים במכונה",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 12,
            weight: 40,
            restTime: 90,
          },
          {
            id: "ex_calf_raises",
            name: "הרמות עקבים",
            muscleGroup: "שוקיים",
            sets: 4,
            reps: 20,
            weight: 60,
            restTime: 60,
          },
          {
            id: "ex_leg_extension",
            name: "פשיטת רגליים במכונה",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 15,
            weight: 35,
            restTime: 90,
          },
        ],
      },
    ],

    metadata: {
      generatedAt: "2024-01-01T10:00:00.000Z",
      difficulty: "intermediate",
      tags: ["כוח", "מסה", "PPL"],
      version: "1.0",
    },
  },

  {
    id: "plan_split_2",
    name: "פיצול עליון/תחתון (Upper/Lower)",
    description: "תוכנית פופולרית לחלוקת אימונים, מתאימה ל-4 אימונים בשבוע.",
    difficulty: "beginner",
    creator: "Gymovo Demo",

    // 📊 נתונים נדרשים
    createdAt: "2024-01-02T10:00:00.000Z",
    updatedAt: "2024-01-02T10:00:00.000Z",
    userId: "demo_user",
    isActive: true,
    rating: 4.2,
    weeklyGoal: 4,
    tags: ["מתחילים", "פיצול", "upper/lower"],

    days: [
      {
        id: "day_upper_1",
        name: "יום א' - חלק עליון",
        estimatedDuration: 55,
        difficulty: "beginner",
        targetMuscleGroups: ["חזה", "גב", "כתפיים", "ידיים"],
        exercises: [
          {
            id: "ex_pushups",
            name: "שכיבות סמיכה",
            muscleGroup: "חזה",
            sets: 3,
            reps: 12,
            restTime: 90,
            notes: "אם קשה - בצע על הברכיים",
          },
          {
            id: "ex_db_row",
            name: "חתירה עם משקולת יחידה",
            muscleGroup: "גב",
            sets: 3,
            reps: 10,
            weight: 20,
            restTime: 90,
          },
          {
            id: "ex_db_shoulder_press",
            name: "לחיצת כתפיים במשקולות",
            muscleGroup: "כתפיים",
            sets: 3,
            reps: 10,
            weight: 12,
            restTime: 90,
          },
          {
            id: "ex_assisted_pullups",
            name: "מתח בעזרה",
            muscleGroup: "גב",
            sets: 3,
            reps: 8,
            restTime: 120,
          },
          {
            id: "ex_db_bicep_curl",
            name: "כפיפת מרפקים במשקולות",
            muscleGroup: "יד קדמית",
            sets: 2,
            reps: 12,
            weight: 10,
            restTime: 60,
          },
          {
            id: "ex_tricep_dips",
            name: "דיפים על ספסל",
            muscleGroup: "יד אחורית",
            sets: 2,
            reps: 10,
            restTime: 60,
          },
        ],
      },
      {
        id: "day_lower_1",
        name: "יום ב' - חלק תחתון",
        estimatedDuration: 50,
        difficulty: "beginner",
        targetMuscleGroups: ["רגליים", "שוקיים"],
        exercises: [
          {
            id: "ex_bodyweight_squat",
            name: "סקוואט במשקל גוף",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 15,
            restTime: 90,
            notes: "התמקד בטכניקה נכונה",
          },
          {
            id: "ex_lunges",
            name: "פילטיס (צעדי אימון)",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 12,
            restTime: 90,
            notes: "6 לכל רגל",
          },
          {
            id: "ex_glute_bridge",
            name: "הרמת ישבן בשכיבה",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 15,
            restTime: 60,
          },
          {
            id: "ex_wall_sit",
            name: "ישיבה על קיר",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 30,
            restTime: 90,
            notes: "30 שניות החזקה",
          },
          {
            id: "ex_standing_calf_raises",
            name: "הרמות עקבים בעמידה",
            muscleGroup: "שוקיים",
            sets: 3,
            reps: 20,
            restTime: 60,
          },
        ],
      },
      {
        id: "day_upper_2",
        name: "יום ג' - חלק עליון (מגוון)",
        estimatedDuration: 55,
        difficulty: "beginner",
        targetMuscleGroups: ["חזה", "גב", "כתפיים", "ידיים"],
        exercises: [
          {
            id: "ex_incline_pushups",
            name: "שכיבות סמיכה בשיפוע",
            muscleGroup: "חזה",
            sets: 3,
            reps: 10,
            restTime: 90,
            notes: "רגליים על ספסל או מדרגה",
          },
          {
            id: "ex_db_chest_fly",
            name: "פתיחות חזה במשקולות",
            muscleGroup: "חזה",
            sets: 3,
            reps: 12,
            weight: 8,
            restTime: 90,
          },
          {
            id: "ex_reverse_fly",
            name: "פתיחות אחוריות",
            muscleGroup: "גב",
            sets: 3,
            reps: 12,
            weight: 5,
            restTime: 90,
          },
          {
            id: "ex_lateral_raises_light",
            name: "הרמות צד קלות",
            muscleGroup: "כתפיים",
            sets: 3,
            reps: 15,
            weight: 3,
            restTime: 60,
          },
          {
            id: "ex_concentration_curl",
            name: "כפיפת ריכוז",
            muscleGroup: "יד קדמית",
            sets: 2,
            reps: 10,
            weight: 8,
            restTime: 60,
          },
        ],
      },
      {
        id: "day_lower_2",
        name: "יום ד' - חלק תחתון (מגוון)",
        estimatedDuration: 50,
        difficulty: "beginner",
        targetMuscleGroups: ["רגליים", "שוקיים"],
        exercises: [
          {
            id: "ex_sumo_squat",
            name: "סקוואט סומו",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 12,
            restTime: 90,
            notes: "רגליים רחבות, בהונות החוצה",
          },
          {
            id: "ex_reverse_lunges",
            name: "פילטיס לאחור",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 10,
            restTime: 90,
            notes: "5 לכל רגל",
          },
          {
            id: "ex_single_leg_deadlift",
            name: "דדליפט על רגל אחת",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 8,
            restTime: 90,
            notes: "4 לכל רגל, משתמש במשקולת קלה",
          },
          {
            id: "ex_squat_pulses",
            name: "דופקי סקוואט",
            muscleGroup: "רגליים",
            sets: 3,
            reps: 20,
            restTime: 60,
            notes: "דופקים קטנים בתחתית הסקוואט",
          },
          {
            id: "ex_seated_calf_raises",
            name: "הרמות עקבים בישיבה",
            muscleGroup: "שוקיים",
            sets: 3,
            reps: 25,
            restTime: 60,
          },
        ],
      },
    ],

    metadata: {
      generatedAt: "2024-01-02T10:00:00.000Z",
      difficulty: "beginner",
      tags: ["מתחילים", "פיצול", "upper/lower"],
      version: "1.0",
    },
  },
];

// 🔧 פונקציות עזר לתוכניות הדמו
export const getDemoPlanById = (id: string): Plan | undefined => {
  return demoPlans.find((plan) => plan.id === id);
};

export const getDemoPlansCount = (): number => {
  return demoPlans.length;
};

export const getDemoPlansCategories = (): string[] => {
  const categories = new Set<string>();
  demoPlans.forEach((plan) => {
    plan.tags?.forEach((tag) => categories.add(tag));
  });
  return Array.from(categories);
};
