// src/constants/demo-users/workouts/aviWorkouts.ts
// 🏋️ היסטוריית אימונים של אבי כהן

import type { DemoWorkoutData } from "./types";

/**
 * 💪 היסטוריית אימונים של אבי כהן
 * מתמחה באימוני Push/Pull/Legs עם משקלים כבדים
 */
export const aviWorkouts: DemoWorkoutData[] = [
  {
    id: "workout-avi-1",
    name: "Push Day - חזה וכתפיים",
    date: new Date("2024-06-01"),
    startTime: "2024-06-01T08:00:00Z",
    endTime: "2024-06-01T09:15:00Z",
    duration: 75,
    exercises: [],
    rating: 5,
    userId: "demo-user-avi",
    totalSets: 20,
    completedSets: 20,
    totalWeight: 22000,
    notes: "אימון מצוין! הרגשתי חזק היום",
    status: "completed",
    planId: "plan-avi-1",
    planName: "תוכנית כוח אבי",
    dayId: "day-1",
    dayName: "Push Day",
    location: "gym",
  },
  {
    id: "workout-avi-2",
    name: "Pull Day - גב ויד קדמית",
    date: new Date("2024-06-03"),
    startTime: "2024-06-03T08:00:00Z",
    endTime: "2024-06-03T09:10:00Z",
    duration: 70,
    exercises: [],
    rating: 4,
    userId: "demo-user-avi",
    totalSets: 18,
    completedSets: 18,
    totalWeight: 18000,
    notes: "קשה במתח, אבל המשכתי",
    status: "completed",
    planId: "plan-avi-1",
    planName: "תוכנית כוח אבי",
    dayId: "day-2",
    dayName: "Pull Day",
    location: "gym",
  },
  {
    id: "workout-avi-3",
    name: "Leg Day - רגליים מלא",
    date: new Date("2024-06-05"),
    startTime: "2024-06-05T08:00:00Z",
    endTime: "2024-06-05T09:20:00Z",
    duration: 80,
    exercises: [],
    rating: 5,
    userId: "demo-user-avi",
    totalSets: 22,
    completedSets: 22,
    totalWeight: 25000,
    notes: "יום רגליים קשה אבל מספק!",
    status: "completed",
    planId: "plan-avi-1",
    planName: "תוכנית כוח אבי",
    dayId: "day-3",
    dayName: "Leg Day",
    location: "gym",
  },
  {
    id: "workout-avi-4",
    name: "Push Day - חזרה",
    date: new Date("2024-06-07"),
    startTime: "2024-06-07T08:00:00Z",
    endTime: "2024-06-07T09:00:00Z",
    duration: 60,
    exercises: [],
    rating: 4,
    userId: "demo-user-avi",
    totalSets: 16,
    completedSets: 16,
    totalWeight: 16000,
    notes: "חזרה על Push Day לשיפור טכניקה",
    status: "completed",
    planId: "plan-avi-1",
    planName: "תוכנית כוח אבי",
    dayId: "day-1",
    dayName: "Push Day",
    location: "gym",
  },
];
