// src/constants/demo-users/workouts/mayaWorkouts.ts
// 🏋️ היסטוריית אימונים של מאיה לוי

import type { DemoWorkoutData } from "./types";

/**
 * 🏃‍♀️ היסטוריית אימונים של מאיה לוי
 * מתמחה באימוני HIIT ואינטרוול לחיטוב וסיבולת
 */
export const mayaWorkouts: DemoWorkoutData[] = [
  {
    id: "workout-maya-1",
    name: "HIIT חלק עליון",
    date: new Date("2024-06-01"),
    startTime: "2024-06-01T08:00:00Z",
    endTime: "2024-06-01T09:00:00Z",
    duration: 60,
    exercises: [],
    rating: 5,
    userId: "demo-user-maya",
    totalSets: 18,
    completedSets: 18,
    totalWeight: 18000,
    notes: "אימון אינטנסיבי ומצוין! הרגשתי בכושר",
    status: "completed",
    planId: "plan-maya-1",
    planName: "תוכנית HIIT מאיה",
    dayId: "day-1",
    dayName: "HIIT עליון",
    location: "gym",
  },
  {
    id: "workout-maya-2",
    name: "כוח רגליים",
    date: new Date("2024-06-03"),
    startTime: "2024-06-03T08:00:00Z",
    endTime: "2024-06-03T09:10:00Z",
    duration: 70,
    exercises: [],
    rating: 4,
    userId: "demo-user-maya",
    totalSets: 20,
    completedSets: 20,
    totalWeight: 20000,
    notes: "הרגליים עבדו קשה היום",
    status: "completed",
    planId: "plan-maya-1",
    planName: "תוכנית HIIT מאיה",
    dayId: "day-2",
    dayName: "כוח רגליים",
    location: "gym",
  },
  {
    id: "workout-maya-3",
    name: "מעגל כל הגוף",
    date: new Date("2024-06-05"),
    startTime: "2024-06-05T08:00:00Z",
    endTime: "2024-06-05T09:05:00Z",
    duration: 65,
    exercises: [],
    rating: 5,
    userId: "demo-user-maya",
    totalSets: 19,
    completedSets: 19,
    totalWeight: 19000,
    notes: "מעגל מהיר ויעיל!",
    status: "completed",
    planId: "plan-maya-1",
    planName: "תוכנית HIIT מאיה",
    dayId: "day-3",
    dayName: "מעגל כל הגוף",
    location: "gym",
  },
  {
    id: "workout-maya-4",
    name: "HIIT חלק עליון",
    date: new Date("2024-06-07"),
    startTime: "2024-06-07T08:00:00Z",
    endTime: "2024-06-07T09:00:00Z",
    duration: 60,
    exercises: [],
    rating: 4,
    userId: "demo-user-maya",
    totalSets: 16,
    completedSets: 16,
    totalWeight: 16000,
    notes: "חזרה על HIIT עליון לשיפור סיבולת",
    status: "completed",
    planId: "plan-maya-1",
    planName: "תוכנית HIIT מאיה",
    dayId: "day-1",
    dayName: "HIIT עליון",
    location: "gym",
  },
];
