// src/constants/demo-users/workouts/yoniWorkouts.ts
// 🏋️ היסטוריית אימונים של יוני רוזן

import type { DemoWorkoutData } from "./types";

/**
 * 🌱 היסטוריית אימונים של יוני רוזן
 * אחרי השאלון: מעבר לתוכנית בניית שריר בחדר כושר
 */
export const yoniWorkouts: DemoWorkoutData[] = [
  {
    id: "workout-yoni-1",
    name: "יום עליון - Full Body",
    date: new Date("2024-06-01"),
    startTime: "2024-06-01T08:00:00Z",
    endTime: "2024-06-01T09:10:00Z",
    duration: 70,
    exercises: [],
    rating: 4,
    userId: "demo-user-yoni",
    totalSets: 16,
    completedSets: 16,
    totalWeight: 9000,
    notes: "תוכנית חדשה! דחיפת חזה בחדר כושר מרגיש טוב",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-1",
    dayName: "יום עליון",
    location: "gym",
  },
  {
    id: "workout-yoni-2",
    name: "יום תחתון - Full Body",
    date: new Date("2024-06-03"),
    startTime: "2024-06-03T08:00:00Z",
    endTime: "2024-06-03T09:00:00Z",
    duration: 60,
    exercises: [],
    rating: 4,
    userId: "demo-user-yoni",
    totalSets: 14,
    completedSets: 14,
    totalWeight: 8000,
    notes: "סקוואט עם משקל - התקדמות מרשימה!",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-2",
    dayName: "יום תחתון",
    location: "gym",
  },
  {
    id: "workout-yoni-3",
    name: "יום מלא - Full Body",
    date: new Date("2024-06-05"),
    startTime: "2024-06-05T08:00:00Z",
    endTime: "2024-06-05T09:05:00Z",
    duration: 65,
    exercises: [],
    rating: 5,
    userId: "demo-user-yoni",
    totalSets: 15,
    completedSets: 15,
    totalWeight: 8500,
    notes: "אימון מלא בחדר כושר! שכיבות סמיכה שלמות",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-3",
    dayName: "יום מלא",
    location: "gym",
  },
  {
    id: "workout-yoni-4",
    name: "יום עליון - חזרה",
    date: new Date("2024-06-07"),
    startTime: "2024-06-07T08:00:00Z",
    endTime: "2024-06-07T09:00:00Z",
    duration: 60,
    exercises: [],
    rating: 4,
    userId: "demo-user-yoni",
    totalSets: 12,
    completedSets: 12,
    totalWeight: 7000,
    notes: "חזרה על יום עליון לשיפור טכניקה",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-1",
    dayName: "יום עליון",
    location: "gym",
  },
  {
    id: "workout-yoni-5",
    name: "יום תחתון - Full Body",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    duration: 30,
    exercises: [],
    rating: 3,
    userId: "demo-user-yoni",
    totalSets: 10,
    completedSets: 7,
    totalWeight: 1400,
    notes: "דחיפת רגליים - עדיין מתרגל",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-2",
    dayName: "יום תחתון",
    location: "gym",
  },
  {
    id: "workout-yoni-6",
    name: "גוף מלא - Full Body",
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    duration: 25,
    exercises: [],
    rating: 4,
    userId: "demo-user-yoni",
    totalSets: 8,
    completedSets: 8,
    totalWeight: 750,
    notes: "התחלה עם התוכנית החדשה - מרגיש טוב!",
    status: "completed",
    planId: "plan-yoni-1",
    planName: "תוכנית יוני",
    dayId: "day-3",
    dayName: "יום מלא",
    location: "gym",
  },
];
